config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  
  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to @note
  end

  private

  def find_note
    @note= Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
 class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
          rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, 
            status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title EVEREVERNOTE | Your Life's Work!
		%meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag "application", "data-turbo-track": "reload"
		= javascript_importmap_tags
	%body
		%header
			.header_inner
				= link_to "EVEREVERNOTE", root_path, id: "logo"
				%nav
					- if user_signed_in?
						= link_to "New Note", new_note_path
						= button_to "Sign Out", destroy_user_session_path, method: :delete 

					- else
						= link_to "Log In", new_user_session_path
		%p.notice= notice
		%p.alert= alert

		= yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.button :submit

app/views/notes/edit.html.haml
%h1 Edit Your Note

= render 'form'

= link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper
	#main_notes
		- @notes.each do |note|
			%h2= link_to note.title, note
			%p= time_ago_in_words(note.created_at)

		= link_to "New Note", new_note_path

app/views/notes/new.html.haml
%h1 Add a new note
= render 'form'

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content

= link_to "All Notes", notes_path

= link_to "Edit", edit_note_path(@note)
= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are You Sure?" }

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 EverEverNote
		%p Your life's Work!
		%button= link_to "Sign Up", new_user_registration_path
#testimonial
	.wrapper
		%p.quote "I keep all our important documents with EverEverNote."
		%p.name - President Obama
#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Journal
				Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

			.callout
				%h2 Notes
				Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

			.callout
				%h2 Epic
				Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

#bottom_cta
	.wrapper
		%h2 Store All Your Notes!
		%p Be Different, Join the Elite!
		%button= link_to "Start Here!!!", new_user_registration_path

%footer
	%p &copy; CrashLearner